baseurl = "https://ziwon.github.io/"
languageCode = "en-us"
title = "人生は儚く短い。"
lightbox = true
copyright = "&copy; <a href=\"https://github.com/ziwon\">Philbert Yoon</a> 2018"
pygmentsstyle = "colorful"
googleAnalytics = "UA-61678624-3"
disqusShortname = "ziwon"
enableRobotsTXT = true
description = "Personal blogs about miscellaneous articles related to Python and Golang"
keywords = ["pythonist", "gopher", "pianist", "cyclist", "programmer"]
paginate = 5
paginatePath = "pages"
theme = "kiss"

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Philbert Yoon" # Author full name
authorEmail = "yngpil.yoon@gmail.com" # Author email

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article

[params.social]
github = "ziwon"
email = "yngpil.yoon@gmail.com"
instagram = "ziwon.y"
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","instagram","email"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
