baseurl = "https://ziwon.github.io/"
languageCode = "en"
title = "人生は儚く短い。"
theme = "kiss"
copyright = "<a href=\"https://github.com/ziwon\">Philbert Yoon</a>"
googleAnalytics = "UA-129419926-1"
disqusShortname = "ziwon"

pygmentsCodefences = true

Paginate = 5
enableRobotsTXT = true

[params.features]
disqusOnDemand = true  # Load Disqus comments on click

[params.assets]
customCSS = ["css/custom.css", "css/syntax.css"]

[params.rss]

includeContent = true # Includes whole content in rss
authorName = "Philbert Yoon" # Site author's full name
authorEmail = "yngpil.yoon@gmail.com"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "theluno"
github = "ziwon"
email = "yngpil.yoon@gmail.com"
instagram = "ziwon.y"

[params.social.config]
platforms = ["twitter","github","email","instagram"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true