baseurl = "https://ziwon.github.io/"
languageCode = "en-us"
title = "人生は儚く短い。"
lightbox = true
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
pygmentsstyle = "colorful"
googleAnalytics = "UA-61678624-3"
description = "Personal blogs about miscellaneous articles related to Python and Golang"
keywords = ["pythonist", "gopher", "pianist", "cyclist", "programmer"]
paginate = 5
paginatePath = "pages"
theme = "hemingway2"

[author]
    name = "Philbert Yoon"

[params]
    disqusShortname = "ziwon"
    hasCJKLanguage = true

[[params.social]]
url = "https://github.com/ziwon"
fa_icon = "fa-github"

[[params.social]]
url = "https://instagram.com/ziwon.y"
fa_icon = "fa-instagram"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
