baseurl = "https://patriz.github.io/"
languageCode = "en-us"
title = "Patriz"
lightbox = true
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "Patrick Yoon"

[params]
    sidebartitle = "Patriz{}"
    sidebartagline = "Developer, Runner, Homeboy"
    disqusShortname = "patriz"

[[menu.main]]
    name = "Blog"
    url = "/posts"

[[menu.main]]
    name = "About"
    url = "/about"

[[menu.social]]
    pre = "<i class='fa fa-instagram'></i>"
    url = "https://instagram.com/theluno"
    identifier = "instagram"

[[menu.social]]
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/patriz"
    identifier = "github"

[[menu.social]] 
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://www.twitter.com/theluno"
    identifier = "twitter"

[[menu.social]]
    pre = "<i class='fa fa-rss'></i>"
    url = "https://patriz.github.io/index.xml"
    identifier = "rss"